version: '2.3'

services:
  ldap:
    image: bitnami/openldap:latest
    build:
      context: ./_meta
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_URI=ldap://openldap:1389
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02,user03
      - LDAP_PASSWORDS=password1,password2,password3
      - LDAP_CUSTOM_LDIF_DIR=./_meta/res
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
