// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package ldap

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "ldap", asset.ModuleFieldsPri, AssetLdap); err != nil {
		panic(err)
	}
}

// AssetLdap returns asset data.
// This is the base64 encoded zlib format compressed contents of module/ldap.
func AssetLdap() string {
	return "eJysks9u2zwQxO96ikHOib6vVx0KFMixKIo2DxCGGslE+Eddrurq7YuVLcdx3AIFsgfB1q5mfhzuHZ65dIi9mxpAg0Z2uPl8/+nrTQMII11lhyeqa4Ce1UuYNJTc4WMDADaK3qmDyz0SVYKv8CVGeptrgCEw9rVbx++QXeLJ0EqXiR1GKfP25oqN1aN99AhfsrqQ68nMjFcC3TnFnkKUJxthj0FKOjBWOvE71qPcOdQl2GH01LqGaHWZzlZ/wLd6Ucc+xIiRmeKUKJngT2bFUMR+yQJhnaMiKFOLh3Lwh+6YEJ1Sbl9J15J4PBWcEG4chaNT9tCC0DNrGEw0ru9Ws3qmcBnIeShHZPvzqr8l88xlX6S/6P0lB6uHHVdF+JKmku3sZThLqN1uDCEjlX6OrP9Zu11StC0YwjiLOy7ZW2h71sn5d0T+xqFIWvMTu6NqQWaVBfdfbsF2bFFkbPnLpSmynSulrs//P1xF1KIuXsWLJY//GKdpbTvjy3yIU3fEm3V+AVjn3gngO3/MzJ7Ic3qibO5+FrG7Pdvm5ncAAAD//9nBRvo="
}
