// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package ldap

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "ldap", asset.ModuleFieldsPri, AssetLdap); err != nil {
		panic(err)
	}
}

// AssetLdap returns asset data.
// This is the base64 encoded zlib format compressed contents of module/ldap.
func AssetLdap() string {
	return "eJx8j0GugyAARPecYuLeC7D4u38QKtOWiEIA03r7BojGEtK3gwlvhhEzdwmrlRdAMslSYsjHQQCBlipS4sakBKAZp2B8Mm6V+BMAykssTm+WArgbWh1lSUasauHpzqTdU+IR3HbcdIzfltYUqcL0PKOeM9MuP+j2Vbr2dsp1Dt9q8eXbV+qemfvLBd1kP9oz/1VYS8UnAAD//1C3bKk="
}
